Repository Say-Their-Name/say-their-names-web, pull requests merged in 2020-06, with the labels that each got.

#33 Restyle homepage to match UI design
  README.md
  public/index.html
  src/assets/black-lives-matter.svg
  src/components/common/Container.js
  src/components/footer/Footer.js
  src/components/footer/style.js
  src/components/profileDetails/PersonProfile.js
  src/components/profileDetails/styles.js
  src/components/ui/getInvolved/GetInvolved.js
  src/components/ui/getInvolved/styles.js
  src/components/ui/media/styles.js
  src/components/ui/profilePreview/ProfilePreview.js
  src/components/ui/profilePreview/styles.js
  src/constants/Color.js
  src/styles/index.js
Labels: WIP

#37 feat:share
  package.json
  src/components/backNavigation/BackNavigation.js
  src/components/backNavigation/styles.js
  src/components/common/Container.js
  src/components/profileDetails/PersonProfile.js
  src/components/profileDetails/button/Button.js
  src/components/profileDetails/button/styles.js
  src/components/profileDetails/share/Share.js
  src/components/profileDetails/share/styles.js
  src/components/profileDetails/styles.js
  src/components/ui/getInvolved/styles.js
  src/pages/ProfileDetail.js
  yarn.lock
Labels: WIP

#55 Setup Google Analytics Page Tracking
  .env.example
  package.json
  src/App.js
  src/routes/index.js
  src/utils/config.js
  src/utils/gaTracker.js
  yarn.lock
Labels: enhancement

#59 chore: fix typo in footer test
  src/components/footer/Footer.test.js
Labels: bug

#72 webview-about update
  src/App.js
  src/components/about/About.js
  src/components/about/About.test.js
  src/components/about/styles.js
  src/pages/AboutPage.js
  src/routes/index.js
Labels: help wanted

#78 Unit test Github Action
  .github/workflows/unit-test.yaml
Labels: enhancement

#125 Fix social media sharing
  src/components/profileDetails/PersonProfile.js
  src/components/ui/actionDetailsHeader/ActionDetailsHeader.js
  src/components/ui/share/Share.js
  src/pages/DonationDetail.js
  src/pages/PetitionDetail.js
Labels: WIP

#141 Accessibility Changes
  package.json
  src/App.js
  src/components/navigation/Navigation.js
  src/components/profileDetails/styles.js
  src/components/ui/profilePreview/styles.js
  src/utils/reactAxe.js
  yarn.lock
Labels: enhancement
